### ISSUE TITLE
[Feat] MVC → MVVM → RxSwift

### ISSUE THREAD

**Issue by EunHee-Jeong** [MVVM-BTS/EunHee#1]
## 프로젝트 소개
- 공공 API를 이용해 어제, 오늘, 내일의 UTC 날짜와 시간을 가져오는 iOS Application

## TODO
- [x] MVC로 초기 프로젝트 만들기
- [x] MVVM 으로 리팩토링
- [x] RxSwift 사용해서 리팩토링
